In [2]:
# Import Librabries 

from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
import os
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [3]:
os.getcwd()

'c:\\Users\\HP\\Desktop\\Machine Learning Programing with prajwal'

In [4]:
# Load Data Set

os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day36\\')


In [5]:
dataset=pd.read_csv('Boost_mushrooms.csv')
dataset

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [6]:

# display the shape

print(dataset.shape)

(8124, 23)


In [7]:
# Check Null Values

print(dataset.isna().sum())

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64


In [8]:
# Data Set Details

print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [9]:
# display Cloumns 

print(dataset.columns)

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')


In [13]:
dataset.columns.shape

(23,)

In [14]:
# Label Encoding

for label in dataset.columns:
    print(label)

class
cap-shape
cap-surface
cap-color
bruises
odor
gill-attachment
gill-spacing
gill-size
gill-color
stalk-shape
stalk-root
stalk-surface-above-ring
stalk-surface-below-ring
stalk-color-above-ring
stalk-color-below-ring
veil-type
veil-color
ring-number
ring-type
spore-print-color
population
habitat


In [16]:
for label in dataset.columns:
    dataset[label]=LabelEncoder().fit(dataset[label]).transform(dataset[label])
display(dataset)    

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [17]:
# Create X

x=dataset.drop(['class'],axis=1)
display(x) 

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 22 columns]

In [19]:
# Create Y

y=dataset['class']
display(y)

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64

In [20]:
# Train Test Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8124, 22)
(5686, 22)
(2438, 22)
(5686,)
(2438,)


In [22]:
# Logistic Regression Model

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print(lr)

LogisticRegression()


In [23]:
# Ada Boost Model with Logistic Regression

AdaBoost=AdaBoostClassifier(estimator=lr,n_estimators=400,learning_rate=1)
lrboostmodel=AdaBoost.fit(x_train,y_train)
print(lrboostmodel)

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(estimator=LogisticRegression(), learning_rate=1,
                   n_estimators=400)


In [24]:
# Predict - Test

lr_pred=lrboostmodel.predict(x_test)
display(lr_pred) 

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [25]:
# Accuracy Score

print(accuracy_score(y_test,lr_pred))

0.9257588187038556


In [27]:
# Confusion Matrix

cm=confusion_matrix(y_test,lr_pred)
display(cm)

array([[1216,   78],
       [ 103, 1041]], dtype=int64)

In [29]:
(1216+1041)/2438

0.9257588187038556

In [28]:
print(y_test.shape)

(2438,)


In [30]:
# Predictions - Complete Data

lr_pred=lrboostmodel.predict(x)
display(lr_pred)

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [31]:
# Accuarcy score

print(accuracy_score(y,lr_pred))

0.9294682422451994


In [32]:
# Confusion Matrix

cm=confusion_matrix(y,lr_pred)
cm

array([[3978,  230],
       [ 343, 3573]], dtype=int64)

In [33]:
# Decision Tree Model

dt_model=DecisionTreeClassifier(criterion='entropy',max_depth=1)
print(dt_model)

DecisionTreeClassifier(criterion='entropy', max_depth=1)


In [34]:
# Ada Boost Model
AdaBoost=AdaBoostClassifier(estimator=dt_model,n_estimators=400,learning_rate=1)
boostmodel=AdaBoost.fit(x_train,y_train)
print(boostmodel) 

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(estimator=DecisionTreeClassifier(criterion='entropy',
                                                    max_depth=1),
                   learning_rate=1, n_estimators=400)


In [35]:
# Predict - Test

dt_pred=boostmodel.predict(x_test)
print(dt_pred)

[1 0 1 ... 0 0 0]


In [36]:
# Accuracy Score - Test

print(accuracy_score(y_test,dt_pred))

1.0


In [37]:
# Confusion Matrix - Test

cm=confusion_matrix(y_test,dt_pred)
print(cm)

[[1294    0]
 [   0 1144]]


In [38]:
# Prediction - Complete Data

dt_pred=boostmodel.predict(x)
print(dt_pred)

[1 0 0 ... 0 1 0]


In [39]:
# Accuracy Score - Complete Data

print(accuracy_score(y,dt_pred))

1.0


In [40]:
# Confuion Matrix - Complete Data

cm=confusion_matrix(y,dt_pred)
cm

array([[4208,    0],
       [   0, 3916]], dtype=int64)

In [41]:
# Create Decision Tree Classifier In Noramal Way

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy')
dt.fit(x_train,y_train)
print(dt)

DecisionTreeClassifier(criterion='entropy')


In [42]:
# Prediction

dt_pred=dt.predict(x_test)
print(dt_pred) 

[1 0 1 ... 0 0 0]


In [43]:
# Accuracy Score

print(accuracy_score(y_test,dt_pred))

1.0


In [44]:
# Confusion Matrix

cm=confusion_matrix(y_test,dt_pred)
cm

array([[1294,    0],
       [   0, 1144]], dtype=int64)

In [47]:
(1294+1144)/2438

1.0

In [46]:
print(y_test.shape)

(2438,)


In [48]:
'''OK Prajwal'''

'OK Prajwal'